name: Update README with Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # ← forces PAT use even during checkout

      - name: Update stats section in README
        run: |
          STATS_URL="https://github-readme-stats.vercel.app/api?username=maxwellagyapong&show_icons=true&count_private=true&theme=tokyonight&cache_seconds=1800"
          NEW_STATS="![GitHub Stats]($STATS_URL)"
          sed -i '/<!--START_STATS-->/, /<!--END_STATS-->/c\<!--START_STATS-->\n'"$NEW_STATS"'\n<!--END_STATS-->' README.md

      - name: Commit and Push README
        run: |
          git config user.name "Maxwell Agyapong"
          git config user.email "35528366+maxwellagyapong@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update GitHub stats"
          git push origin HEAD:main
